/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CompaniesHouseSearch {
        "debounce": number;
        "placeholder": string;
        "token": string;
    }
}
declare global {
    interface HTMLCompaniesHouseSearchElement extends Components.CompaniesHouseSearch, HTMLStencilElement {
    }
    var HTMLCompaniesHouseSearchElement: {
        prototype: HTMLCompaniesHouseSearchElement;
        new (): HTMLCompaniesHouseSearchElement;
    };
    interface HTMLElementTagNameMap {
        "companies-house-search": HTMLCompaniesHouseSearchElement;
    }
}
declare namespace LocalJSX {
    interface CompaniesHouseSearch {
        "debounce"?: number;
        "onBusinessSelected"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "token"?: string;
    }
    interface IntrinsicElements {
        "companies-house-search": CompaniesHouseSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "companies-house-search": LocalJSX.CompaniesHouseSearch & JSXBase.HTMLAttributes<HTMLCompaniesHouseSearchElement>;
        }
    }
}
